services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Jorgee-54
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data